// 热门课程分类
const hot_course_types=[
  {"course_type":"Java视频","sub_course_types":["Java基础","JavaSE","教程1","教程2","教程3","教程4","教程5","教程6","教程7","Java基础","JavaSE","教程1","教程2","教程3","教程4","教程5","教程6","教程7"]},
  {"course_type":"Python视频","sub_course_types":["Python基础","Python入门","Java基础","JavaSE","教程1","教程2","教程3","教程4","教程5","教程6","教程7","Java基础","JavaSE","教程1","教程2","教程3","教程4","教程5","教程6","教程7"]},
  {"course_type":"Golang视频","sub_course_types":["Golang基础","Golang入门","Java基础","JavaSE","教程1","教程2","教程3","教程4","教程5","教程6","教程7","Java基础","JavaSE","教程1","教程2","教程3","教程4","教程5","教程6","教程7"]},
  {"course_type":"HTML教程","sub_course_types":["Golang基础","Golang入门","Java基础","JavaSE","教程1","教程2","教程3","教程4","教程5","教程6","教程7","Java基础","JavaSE","教程1","教程2","教程3","教程4","教程5","教程6","教程7"]},
  {"course_type":"前端教程","sub_course_types":["Golang基础","Golang入门","Java基础","JavaSE","教程1","教程2","教程3","教程4","教程5","教程6","教程7","Java基础","JavaSE","教程1","教程2","教程3","教程4","教程5","教程6","教程7"]},
  {"course_type":"后端教程","sub_course_types":["Java基础","JavaSE","教程1","教程2","教程3","教程4","教程5","教程6","教程7","Java基础","JavaSE","教程1","教程2","教程3","教程4","教程5","教程6","教程7","Golang基础","Golang入门"]},
  {"course_type":"数据库教程","sub_course_types":["Golang基础","Java基础","JavaSE","教程1","教程2","教程3","教程4","教程5","教程6","教程7","Java基础","JavaSE","教程1","教程2","教程3","教程4","教程5","教程6","教程7","Golang入门"]},
  {"course_type":"测试教程","sub_course_types":["Golang基础","Golang入门","Java基础","JavaSE","教程1","教程2","教程3","教程4","教程5","教程6","教程7","Java基础","JavaSE","教程1","教程2","教程3","教程4","教程5","教程6","教程7","Java基础","JavaSE","教程1","教程2","教程3","教程4","教程5","教程6","教程7","Java基础","JavaSE","教程1","教程2","教程3","教程4","教程5","教程6","教程7"]},
];

// 热门分享类型
const hot_share_type=[
  {
    "name":"Java社区",
    "img":"/static/images/java_50_50.jpg",
    "detail":"简单、直观、强悍，一次编译，到处运行。",
  },
  {
    "name":"Python社区",
    "img":"/static/images/python_50_50.jpg",
    "detail":"简单、易学、免费/开源，丰富而且强大的库。",
  },
  {
    "name":"Golang社区",
    "img":"/static/images/golang_50_50.jpg",
    "detail":"执行速度和开发效率出色，语言级别上支持协程并发。",
  },
  {
    "name":"招聘空间",
    "img":"/static/images/job_50_50.jpg",
    "detail":"简洁、直观、强悍的前端框架，让web开发更迅速简单。",
  },
  {
    "name":"Java社区",
    "img":"/static/images/golang_50_50.jpg",
    "detail":"简洁、直观、强悍的前端框架，让web开发更迅速简单。",
  },
  {
    "name":"Java社区",
    "img":"/static/images/golang_50_50.jpg",
    "detail":"简洁、直观、强悍的前端框架，让web开发更迅速简单。",
  },
  {
    "name":"Java社区",
    "img":"/static/images/golang_50_50.jpg",
    "detail":"简洁、直观、强悍的前端框架，让web开发更迅速简单。",
  },
  {
    "name":"Java社区",
    "img":"/static/images/golang_50_50.jpg",
    "detail":"简洁、直观、强悍的前端框架，让web开发更迅速简单。",
  },
  {
    "name":"Java社区",
    "img":"/static/images/java_50_50.jpg",
    "detail":"简单、直观、强悍，一次编译，到处运行。",
  },
  {
    "name":"Python社区",
    "img":"/static/images/python_50_50.jpg",
    "detail":"简单、易学、免费/开源，丰富而且强大的库。",
  },
  {
    "name":"Golang社区",
    "img":"/static/images/golang_50_50.jpg",
    "detail":"执行速度和开发效率出色，语言级别上支持协程并发。",
  },
  {
    "name":"招聘空间",
    "img":"/static/images/job_50_50.jpg",
    "detail":"简洁、直观、强悍的前端框架，让web开发更迅速简单。",
  },
];

export default {
  hot_course_types,
  hot_share_type,
}
